Survive: TutorialWidget Class Reference
TutorialWidget Class Reference
#include <tutorialwidget.h>
Signals
void close ()
Public Member Functions
TutorialWidget (QWidget *parent=nullptr)
~TutorialWidget ()
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Member Functions
void paintEvent (QPaintEvent *event) override
Paint event handler. See QWidget paint.
void loadGraphics ()
Loads graphics for the widget.
void setupUi ()
Sets up the UI.
Private Attributes
QSvgWidget * bannerWidget
ScalableLabel * bodyLabel
SVGPushButton * closeButton
QPixmap overlay
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Constructor & Destructor Documentation
TutorialWidget()
TutorialWidget::TutorialWidget (QWidget * parent = nullptr)
~TutorialWidget()
TutorialWidget::~TutorialWidget ()
Member Function Documentation
close
void TutorialWidget::close () signal
Referenced by Game::onHelp(), and setupUi().
loadGraphics()
void TutorialWidget::loadGraphics () private
Loads graphics for the widget.
Referenced by TutorialWidget().
paintEvent()
void TutorialWidget::paintEvent (QPaintEvent * event) override private
Paint event handler. See QWidget paint.
Parameters
event The event
setupUi()
void TutorialWidget::setupUi () private
Sets up the UI.
Referenced by TutorialWidget().
Member Data Documentation
bannerWidget
QSvgWidget* TutorialWidget::bannerWidget private
Referenced by setupUi().
bodyLabel
ScalableLabel* TutorialWidget::bodyLabel private
Referenced by setupUi().
closeButton
SVGPushButton* TutorialWidget::closeButton private
Referenced by setupUi().
overlay
QPixmap TutorialWidget::overlay private
Referenced by loadGraphics(), and paintEvent().
The documentation for this class was generated from the following files:
tutorialwidget.h
tutorialwidget.cpp