var annotated_dup =
[
    [ "Action", "db/d09/classAction.html", "db/d09/classAction" ],
    [ "ActionInfo", "de/dc4/structActionInfo.html", "de/dc4/structActionInfo" ],
    [ "ActionResult", "d9/ddf/structActionResult.html", "d9/ddf/structActionResult" ],
    [ "Animal", "d7/dac/classAnimal.html", "d7/dac/classAnimal" ],
    [ "AnimalInfo", "d3/d93/structAnimalInfo.html", "d3/d93/structAnimalInfo" ],
    [ "Bar", "d7/d9a/classBar.html", "d7/d9a/classBar" ],
    [ "ClimateData", "dd/d8f/structClimateData.html", "dd/d8f/structClimateData" ],
    [ "Day", "d8/d0d/classDay.html", "d8/d0d/classDay" ],
    [ "DraggableWidget", "d6/d1f/classDraggableWidget.html", "d6/d1f/classDraggableWidget" ],
    [ "Engine", "d1/db6/classEngine.html", "d1/db6/classEngine" ],
    [ "Event", "d5/da5/classEvent.html", "d5/da5/classEvent" ],
    [ "EventInfo", "d2/d31/structEventInfo.html", "d2/d31/structEventInfo" ],
    [ "EventResult", "d0/d28/structEventResult.html", "d0/d28/structEventResult" ],
    [ "Explore", "de/d27/classExplore.html", "de/d27/classExplore" ],
    [ "ExploreInfo", "d7/d06/structExploreInfo.html", "d7/d06/structExploreInfo" ],
    [ "Game", "d9/d68/classGame.html", "d9/d68/classGame" ],
    [ "Level", "d2/d9d/classLevel.html", "d2/d9d/classLevel" ],
    [ "LevelConfig", "d5/d26/structLevelConfig.html", "d5/d26/structLevelConfig" ],
    [ "LevelInfo", "de/d3c/structLevelInfo.html", "de/d3c/structLevelInfo" ],
    [ "LevelInfoWidget", "da/d89/classLevelInfoWidget.html", "da/d89/classLevelInfoWidget" ],
    [ "LoadGameMenu", "da/d1e/classLoadGameMenu.html", "da/d1e/classLoadGameMenu" ],
    [ "MainMenu", "d9/d0a/classMainMenu.html", "d9/d0a/classMainMenu" ],
    [ "Menu", "d8/ddb/classMenu.html", "d8/ddb/classMenu" ],
    [ "NewGameMenu", "d7/d63/classNewGameMenu.html", "d7/d63/classNewGameMenu" ],
    [ "NotebookWidget", "db/d4c/classNotebookWidget.html", "db/d4c/classNotebookWidget" ],
    [ "Plant", "d9/d6e/classPlant.html", "d9/d6e/classPlant" ],
    [ "PlantInfo", "d0/d4a/structPlantInfo.html", "d0/d4a/structPlantInfo" ],
    [ "Precipitation", "da/dbb/structPrecipitation.html", "da/dbb/structPrecipitation" ],
    [ "ResultWidget", "d2/dad/classResultWidget.html", "d2/dad/classResultWidget" ],
    [ "ScalableWidget", "de/d1f/classScalableWidget.html", "de/d1f/classScalableWidget" ],
    [ "Season", "d4/d42/classSeason.html", "d4/d42/classSeason" ],
    [ "SettingsMenu", "db/dbe/classSettingsMenu.html", "db/dbe/classSettingsMenu" ],
    [ "SurviveGame", "dd/d67/classSurviveGame.html", "dd/d67/classSurviveGame" ],
    [ "SVGPushButton", "d7/d1f/classSVGPushButton.html", "d7/d1f/classSVGPushButton" ],
    [ "Temperature", "da/dfe/structTemperature.html", "da/dfe/structTemperature" ]
];