Survive: Level Class Reference
Level Class Reference
This class describes the level instance.
#include <level.h>
Public Member Functions
Level (const QString &id)
Constructs a new level instance.
Level (const Level &level)
Copy constructor to copy a level.
~Level ()
Destroys the object.
QString file (const QString &name) const
Gets a file path from inside the level folder.
const LevelInfo & getInfo () const
Gets the level info.
const LevelConfig & getConfig () const
Gets the level configuration.
const Animal & getAnimals () const
Gets the animal data.
const Event & getEvents () const
Gets the events data.
const Explore & getExplorer () const
Gets the explore events data.
const Plant & getPlants () const
Gets the plants data.
const Season & getSeasons () const
Gets the seasons data.
Private Member Functions
void loadLevel ()
Loads a level.
Private Attributes
LevelInfo info
LevelConfig config
Animal animals
Event events
Explore explorer
Plant plants
Season seasons
Detailed Description
This class describes the level instance.
Constructor & Destructor Documentation
Level() [1/2]
Level::Level (const QString & id)
Constructs a new level instance.
Parameters
[in] id The level identifier
Level() [2/2]
Level::Level (const Level & level)
Copy constructor to copy a level.
Parameters
[in] level The level
~Level()
Level::~Level ()
Destroys the object.
Member Function Documentation
file()
QString Level::file (const QString & name) const
Gets a file path from inside the level folder.
Parameters
[in] name The name of the file
Returns
The file path.
Referenced by Engine::Engine(), and loadLevel().
getAnimals()
const Animal & Level::getAnimals () const
Gets the animal data.
Returns
The animals.
getConfig()
const LevelConfig & Level::getConfig () const
Gets the level configuration.
Returns
The level configuration.
Referenced by Engine::triggerDayEvent().
getEvents()
const Event & Level::getEvents () const
Gets the events data.
Returns
The events.
Referenced by Engine::triggerDayEvent().
getExplorer()
const Explore & Level::getExplorer () const
Gets the explore events data.
Returns
The explore events.
Referenced by Engine::explore().
getInfo()
const LevelInfo & Level::getInfo () const
Gets the level info.
Returns
The level info.
Referenced by Game::textureFile().
getPlants()
const Plant & Level::getPlants () const
Gets the plants data.
Returns
The plants.
getSeasons()
const Season & Level::getSeasons () const
Gets the seasons data.
Returns
The seasons.
Referenced by Engine::triggerDayEvent().
loadLevel()
void Level::loadLevel () private
Loads a level.
Referenced by Level().
Member Data Documentation
animals
Animal Level::animals private
The animals.
Referenced by getAnimals().
config
LevelConfig Level::config private
Gets the level config.
Referenced by getConfig().
events
Event Level::events private
The events.
Referenced by getEvents().
explorer
Explore Level::explorer private
The explore events.
Referenced by getExplorer().
info
LevelInfo Level::info private
The level information.
Referenced by file(), getInfo(), and loadLevel().
plants
Plant Level::plants private
The plants.
Referenced by getPlants().
seasons
Season Level::seasons private
The seasons.
Referenced by getSeasons().
The documentation for this class was generated from the following files:
level.h
level.cpp