Survive: ActionMenu Class Reference
ActionMenu Class Reference
This class describes the action menu within the notebook.
#include <actionmenu.h>
Signals
void findFood ()
Signal that the user has opted to find food.
void findWater ()
Signal that the user has opted to find water.
void explore ()
Signal that the user has opted to explore.
void rest ()
Signal that the user has opted to rest.
Public Member Functions
ActionMenu (QWidget *parent=nullptr)
Constructs a new instance.
~ActionMenu ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Member Functions
void setupUi ()
Sets up the UI.
Private Attributes
SVGPushButton * findFoodButton
SVGPushButton * findWaterButton
SVGPushButton * exploreButton
SVGPushButton * restButton
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes the action menu within the notebook.
Constructor & Destructor Documentation
ActionMenu()
ActionMenu::ActionMenu (QWidget * parent = nullptr) explicit
Constructs a new instance.
Parameters
parent The parent
~ActionMenu()
ActionMenu::~ActionMenu ()
Destroys the object.
Member Function Documentation
explore
void ActionMenu::explore () signal
Signal that the user has opted to explore.
Referenced by NotebookWidget::displayActionMenu(), and setupUi().
findFood
void ActionMenu::findFood () signal
Signal that the user has opted to find food.
Referenced by NotebookWidget::displayActionMenu(), and setupUi().
findWater
void ActionMenu::findWater () signal
Signal that the user has opted to find water.
Referenced by NotebookWidget::displayActionMenu(), and setupUi().
rest
void ActionMenu::rest () signal
Signal that the user has opted to rest.
Referenced by NotebookWidget::displayActionMenu(), and setupUi().
setupUi()
void ActionMenu::setupUi () private
Sets up the UI.
Referenced by ActionMenu().
Member Data Documentation
exploreButton
SVGPushButton* ActionMenu::exploreButton private
Referenced by setupUi().
findFoodButton
SVGPushButton* ActionMenu::findFoodButton private
Referenced by setupUi().
findWaterButton
SVGPushButton* ActionMenu::findWaterButton private
Referenced by setupUi().
restButton
SVGPushButton* ActionMenu::restButton private
Referenced by setupUi().
The documentation for this class was generated from the following files:
actionmenu.h
actionmenu.cpp