Survive: Journal Class Reference
Journal Class Reference
This class describes a journal for storing game events.
#include <journal.h>
Public Member Functions
Journal ()
Constructs a new journal instance.
~Journal ()
Destroys the object.
void addDay (int day, const QString &dayEvent="There was no start of day event.")
Adds a day to the journal.
void addEntry (int day, ActionEntry entry)
Adds an action entry to a day.
int getDayCount () const
Gets the day count.
DayEntry getEntry (int day) const
Gets the entry for a given day.
Private Attributes
QMap< int, DayEntry > entries
Detailed Description
This class describes a journal for storing game events.
Constructor & Destructor Documentation
Journal()
Journal::Journal ()
Constructs a new journal instance.
~Journal()
Journal::~Journal ()
Destroys the object.
Member Function Documentation
addDay()
void Journal::addDay (int day, const QString & dayEvent = "There was no start of day event.")
Adds a day to the journal.
Parameters
[in] day The day
[in] dayEvent The day event
Referenced by Engine::Engine(), Engine::loadFromFile(), and Engine::triggerDayEvent().
addEntry()
void Journal::addEntry (int day, ActionEntry entry)
Adds an action entry to a day.
Parameters
[in] day The day
[in] entry The entry
Referenced by Engine::loadFromFile().
getDayCount()
int Journal::getDayCount () const
Gets the day count.
Returns
The day count.
Referenced by Engine::dump(), and HistoryWidget::setupUi().
getEntry()
DayEntry Journal::getEntry (int day) const
Gets the entry for a given day.
Parameters
[in] day The day
Returns
The entry.
Referenced by Engine::dump(), and HistoryWidget::showDay().
Member Data Documentation
entries
QMap<int, DayEntry> Journal::entries private
Maps the days to the journal entries.
Referenced by addDay(), addEntry(), getDayCount(), and getEntry().
The documentation for this class was generated from the following files:
journal.h
journal.cpp