Survive: Menu Class Reference
Menu Class Reference
This class describes the mainmenu menu.
#include <menu.h>
Signals
void newGameMenuOpened ()
Emitted when the new game menu is opened.
void loadGameMenuOpened ()
Emitted when the load game menu is opened.
void settingsMenuOpened ()
Emitted when the settings menu is opened.
Public Member Functions
Menu (QWidget *parent=nullptr)
Creates a new menu instance.
~Menu ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Member Functions
void paintEvent (QPaintEvent *event) override
Paint event handler. See QWidget paint.
void loadGraphics ()
Loads graphics for the widget.
void setupUi ()
Sets up the UI.
Private Attributes
QSvgWidget * menuTitle
SVGPushButton * newGameButton
SVGPushButton * loadGameButton
SVGPushButton * settingsButton
SVGPushButton * exitButton
QPixmap background
QPixmap overlay1
QPixmap overlay2
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes the mainmenu menu.
Constructor & Destructor Documentation
Menu()
Menu::Menu (QWidget * parent = nullptr) explicit
Creates a new menu instance.
Parameters
parent The parent
~Menu()
Menu::~Menu ()
Destroys the object.
Member Function Documentation
loadGameMenuOpened
void Menu::loadGameMenuOpened () signal
Emitted when the load game menu is opened.
Referenced by MainMenu::MainMenu(), and setupUi().
loadGraphics()
void Menu::loadGraphics () private
Loads graphics for the widget.
Referenced by Menu().
newGameMenuOpened
void Menu::newGameMenuOpened () signal
Emitted when the new game menu is opened.
Referenced by MainMenu::MainMenu(), and setupUi().
paintEvent()
void Menu::paintEvent (QPaintEvent * event) override private
Paint event handler. See QWidget paint.
Parameters
event The event
settingsMenuOpened
void Menu::settingsMenuOpened () signal
Emitted when the settings menu is opened.
Referenced by MainMenu::MainMenu(), and setupUi().
setupUi()
void Menu::setupUi () private
Sets up the UI.
Referenced by Menu().
Member Data Documentation
background
QPixmap Menu::background private
Referenced by loadGraphics(), and paintEvent().
exitButton
SVGPushButton* Menu::exitButton private
Referenced by setupUi(), and ~Menu().
loadGameButton
SVGPushButton* Menu::loadGameButton private
Referenced by setupUi(), and ~Menu().
menuTitle
QSvgWidget* Menu::menuTitle private
Referenced by setupUi(), and ~Menu().
newGameButton
SVGPushButton* Menu::newGameButton private
Referenced by setupUi(), and ~Menu().
overlay1
QPixmap Menu::overlay1 private
Referenced by loadGraphics(), and paintEvent().
overlay2
QPixmap Menu::overlay2 private
Referenced by loadGraphics(), and paintEvent().
settingsButton
SVGPushButton* Menu::settingsButton private
Referenced by setupUi(), and ~Menu().
The documentation for this class was generated from the following files:
menu.h
menu.cpp