Survive: Season Class Reference
Season Class Reference
This class describes the season instance.
#include <season.h>
Public Member Functions
Season (const QString &filename)
QString getSeason (const QString &month) const
QStringList getMonth (const QString &season) const
Private Attributes
QMap< QString, QString > monthToSeason
Detailed Description
This class describes the season instance.
Constructor & Destructor Documentation
Season()
Season::Season (const QString & filename)
Member Function Documentation
getMonth()
QStringList Season::getMonth (const QString & season) const
getSeason()
QString Season::getSeason (const QString & month) const
Referenced by Game::correctSeason(), Engine::triggerDayEvent(), and Game::triggerEvent().
Member Data Documentation
monthToSeason
QMap<QString, QString> Season::monthToSeason private
Referenced by getMonth(), getSeason(), and Season().
The documentation for this class was generated from the following files:
season.h
season.cpp