Survive: GameOver Class Reference
GameOver Class Reference
This class describes the game over screen.
#include <gameover.h>
Signals
void close ()
Called when the user closes the widget.
Public Member Functions
GameOver (QWidget *parent=nullptr)
Constructs a new instance.
~GameOver ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Member Functions
void paintEvent (QPaintEvent *event) override
Paint event handler. See QWidget paint.
void loadGraphics ()
Loads the widget's graphics.
void setupUi ()
Sets up the UI.
Private Attributes
QPixmap background
SVGPushButton * closeButton
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes the game over screen.
Constructor & Destructor Documentation
GameOver()
GameOver::GameOver (QWidget * parent = nullptr) explicit
Constructs a new instance.
Parameters
parent The parent
~GameOver()
GameOver::~GameOver ()
Destroys the object.
Member Function Documentation
close
void GameOver::close () signal
Called when the user closes the widget.
Referenced by Game::endGame(), and setupUi().
loadGraphics()
void GameOver::loadGraphics () private
Loads the widget's graphics.
Referenced by GameOver().
paintEvent()
void GameOver::paintEvent (QPaintEvent * event) override private
Paint event handler. See QWidget paint.
Parameters
event The event
setupUi()
void GameOver::setupUi () private
Sets up the UI.
Referenced by GameOver().
Member Data Documentation
background
QPixmap GameOver::background private
Referenced by loadGraphics(), and paintEvent().
closeButton
SVGPushButton* GameOver::closeButton private
Referenced by setupUi().
The documentation for this class was generated from the following files:
gameover.h
gameover.cpp