Survive: Bar Class Reference
Bar Class Reference
This class describes a users bar.
#include <bar.h>
Public Member Functions
Bar (int initialVal)
Constructs a new bar with an initial value.
Bar ()
Constructs a new bar with the default max value..
~Bar ()
Destroys the object.
int plus (int val)
Additive update to the bars value.
int minus (int val)
Reductive update to the bars value.
int getValue () const
Gets the value.
bool isEmpty () const
Determines if bar is empty.
Private Attributes
int dataval
Detailed Description
This class describes a users bar.
Constructor & Destructor Documentation
Bar() [1/2]
Bar::Bar (int initialVal)
Constructs a new bar with an initial value.
Parameters
[in] initialVal The initial value
Bar() [2/2]
Bar::Bar ()
Constructs a new bar with the default max value..
~Bar()
Bar::~Bar ()
Destroys the object.
Member Function Documentation
getValue()
int Bar::getValue () const
Gets the value.
Returns
The value.
Referenced by Engine::getEnergy(), Engine::getHealth(), Engine::getHunger(), Engine::getThirst(), and Engine::rest().
isEmpty()
bool Bar::isEmpty () const
Determines if bar is empty.
Returns
True if empty, False otherwise.
Referenced by Engine::isGameOver().
minus()
int Bar::minus (int val)
Reductive update to the bars value.
Parameters
[in] val The value
Returns
The updated value.
Referenced by Engine::explore(), Engine::findFood(), Engine::findWater(), and Engine::rest().
plus()
int Bar::plus (int val)
Additive update to the bars value.
Parameters
[in] val The value
Returns
The updated value.
Referenced by Engine::affectBars(), Engine::findWater(), and Engine::rest().
Member Data Documentation
dataval
int Bar::dataval private
Value of the bar.
Referenced by Bar(), getValue(), isEmpty(), minus(), and plus().
The documentation for this class was generated from the following files:
bar.h
bar.cpp