Survive: SurviveGame Class Reference
SurviveGame Class Reference
This class describes the base main window of the game.
#include <survivegame.h>
Public Member Functions
SurviveGame (QWidget *parent=nullptr)
Create a new main window.
~SurviveGame ()
Destroys the object.
Private Slots
void onNewGame (const QString &id)
Called when a new game is selected.
void onReturnToMenu ()
Called when the user wants to return to the main menu.
Private Member Functions
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void setupUiSettings ()
Sets up the UI based on the user settings.
void setupUi ()
Set up the main window UI.
Private Attributes
MainMenu * mainMenu
Game * game
bool windowSizeInitialized = false
Detailed Description
This class describes the base main window of the game.
Constructor & Destructor Documentation
SurviveGame()
SurviveGame::SurviveGame (QWidget * parent = nullptr) explicit
Create a new main window.
Parameters
parent The parent
~SurviveGame()
SurviveGame::~SurviveGame ()
Destroys the object.
Member Function Documentation
onNewGame
void SurviveGame::onNewGame (const QString & id) private slot
Called when a new game is selected.
Parameters
[in] id The identifier of the level
Referenced by onReturnToMenu().
onReturnToMenu
void SurviveGame::onReturnToMenu () private slot
Called when the user wants to return to the main menu.
Referenced by onNewGame(), and setupUi().
resizeEvent()
void SurviveGame::resizeEvent (QResizeEvent * event) override private
Resize event handler.
Parameters
event The event
setupUi()
void SurviveGame::setupUi () private
Set up the main window UI.
Referenced by resizeEvent().
setupUiSettings()
void SurviveGame::setupUiSettings () private
Sets up the UI based on the user settings.
Referenced by onReturnToMenu(), and SurviveGame().
Member Data Documentation
game
Game* SurviveGame::game private
Game instance.
Referenced by onNewGame().
mainMenu
MainMenu* SurviveGame::mainMenu private
Main menu for the game.
Referenced by onReturnToMenu().
windowSizeInitialized
bool SurviveGame::windowSizeInitialized = false private
Referenced by resizeEvent().
The documentation for this class was generated from the following files:
survivegame.h
survivegame.cpp