Survive: SettingsMenu Class Reference
SettingsMenu Class Reference
This class describes a settings menu.
#include <settingsmenu.h>
Signals
void resolutionOptionChanged (QSize resolution)
Emitted when the resolution option is changed.
void frameOptionChanged (int frame)
Emitted when the frame option is changed.
void settingsMenuClosed ()
Emitted when the settings menu is closed.
Public Member Functions
SettingsMenu (QWidget *parent=nullptr)
Creates a new settings menu.
~SettingsMenu ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Slots
void onResolutionOptionChanged ()
Called when resolution option changed.
void onFrameOptionChanged ()
Called when frame option changed.
void onSettingsMenuClosed ()
Called when settings menu closed.
Private Member Functions
void paintEvent (QPaintEvent *event) override
Paint event handler. See QWidget paint.
void loadStylesheet ()
Loads the stylesheet.
void loadGraphics ()
Loads the graphics.
void setupUi ()
Sets up the UI.
Private Attributes
QSettings * settings
QSvgWidget * title
QSvgWidget * resolutionLabel
QComboBox * resolutionOption
QComboBox * frameOption
SVGPushButton * backButton
QPixmap background
QPixmap overlay1
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes a settings menu.
Constructor & Destructor Documentation
SettingsMenu()
SettingsMenu::SettingsMenu (QWidget * parent = nullptr)
Creates a new settings menu.
Parameters
parent The parent
~SettingsMenu()
SettingsMenu::~SettingsMenu ()
Destroys the object.
Member Function Documentation
frameOptionChanged
void SettingsMenu::frameOptionChanged (int frame) signal
Emitted when the frame option is changed.
Parameters
[in] frame The frame
Referenced by MainMenu::displaySettingsMenu(), and onFrameOptionChanged().
loadGraphics()
void SettingsMenu::loadGraphics () private
Loads the graphics.
Referenced by SettingsMenu().
loadStylesheet()
void SettingsMenu::loadStylesheet () private
Loads the stylesheet.
Referenced by SettingsMenu().
onFrameOptionChanged
void SettingsMenu::onFrameOptionChanged () private slot
Called when frame option changed.
Referenced by setupUi().
onResolutionOptionChanged
void SettingsMenu::onResolutionOptionChanged () private slot
Called when resolution option changed.
Referenced by setupUi().
onSettingsMenuClosed
void SettingsMenu::onSettingsMenuClosed () private slot
Called when settings menu closed.
Referenced by setupUi().
paintEvent()
void SettingsMenu::paintEvent (QPaintEvent * event) override private
Paint event handler. See QWidget paint.
Parameters
event The event
resolutionOptionChanged
void SettingsMenu::resolutionOptionChanged (QSize resolution) signal
Emitted when the resolution option is changed.
Parameters
[in] resolution The resolution
Referenced by MainMenu::displaySettingsMenu(), and onResolutionOptionChanged().
settingsMenuClosed
void SettingsMenu::settingsMenuClosed () signal
Emitted when the settings menu is closed.
Referenced by MainMenu::displaySettingsMenu(), and onSettingsMenuClosed().
setupUi()
void SettingsMenu::setupUi () private
Sets up the UI.
Referenced by SettingsMenu().
Member Data Documentation
backButton
SVGPushButton* SettingsMenu::backButton private
Referenced by setupUi().
background
QPixmap SettingsMenu::background private
Referenced by loadGraphics(), and paintEvent().
frameOption
QComboBox* SettingsMenu::frameOption private
Referenced by onFrameOptionChanged(), setupUi(), and ~SettingsMenu().
overlay1
QPixmap SettingsMenu::overlay1 private
Referenced by loadGraphics(), and paintEvent().
resolutionLabel
QSvgWidget* SettingsMenu::resolutionLabel private
Referenced by setupUi(), and ~SettingsMenu().
resolutionOption
QComboBox* SettingsMenu::resolutionOption private
Referenced by onResolutionOptionChanged(), setupUi(), and ~SettingsMenu().
settings
QSettings* SettingsMenu::settings private
Referenced by onFrameOptionChanged(), onResolutionOptionChanged(), SettingsMenu(), setupUi(), and ~SettingsMenu().
title
QSvgWidget* SettingsMenu::title private
Referenced by setupUi(), and ~SettingsMenu().
The documentation for this class was generated from the following files:
settingsmenu.h
settingsmenu.cpp