Survive: NotebookWidget Class Reference
NotebookWidget Class Reference
This class describes a notebook widget in the game.
#include <notebookwidget.h>
Classes
struct WidgetInfo
Information of the notebook widgets.
Signals
void findFood ()
Called when the user has opted to find food.
void findWater ()
Called when the user has opted to find water.
void explore ()
Called when the user has opted to explore.
void rest ()
Called when the user has opted to rest.
void sleep ()
Called when the user has opted to sleep.
void resultAcknowledged ()
Called when the user has acknowledged the result widget.
void close ()
Called when the user closes the notebook.
Public Member Functions
NotebookWidget (const Engine &engine, QWidget *parent=nullptr)
Constructs a new instance.
~NotebookWidget ()
Destroys the object.
void displayActionMenu (bool hide=false)
Displays the menu for selecting an action.
void displayHistoryWidget (int day=-1, bool hide=true)
Displays the history widget for journal entries.
void displayResultsWidget (QString action, QString result, bool hide=true)
Display the results to a user.
void displaySleepWidget (bool hide=true)
Display the option for the user to sleep.
void updateDay ()
Updates the day text.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Types
enum class WidgetType { ACTION_MENU , HISTORY_WIDGET , RESULTS_WIDGET , SLEEP_WIDGET }
Enum representing the type of widget being displayed.
Private Member Functions
void paintEvent (QPaintEvent *event) override
Paint event handler. See QWidget paint.
void loadStylesheet ()
Loads a stylesheet.
void loadGraphics ()
Loads the widget's graphics.
void setupUi ()
Sets up the UI.
void raiseButtons ()
Raises the buttons to be on top.
void displayPrevious ()
Displays the previous widget on the stack.
void closeCurrent (bool hide=false)
Closes the current widget on the stack.
void closeActionMenu (bool hide=false)
Closes the action menu.
void closeHistoryWidget (bool hide=false)
Closes the history widget.
void closeResultsWidget (bool hide=false)
Closes the results widget.
void closeSleepWidget (bool hide=false)
Closes the sleep widget.
Private Attributes
const Engine & engine
QList< WidgetInfo > widgetStack
ActionMenu * actionMenu = nullptr
HistoryWidget * historyWidget
ResultWidget * resultWidget
SleepWidget * sleepWidget
ScalableLabel * titleLabel
SVGPushButton * historyButton
SVGPushButton * closeButton
QPixmap background
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes a notebook widget in the game.
Member Enumeration Documentation
WidgetType
enum NotebookWidget::WidgetType strong private
Enum representing the type of widget being displayed.
Enumerator
ACTION_MENU
HISTORY_WIDGET
RESULTS_WIDGET
SLEEP_WIDGET
Constructor & Destructor Documentation
NotebookWidget()
NotebookWidget::NotebookWidget (const Engine & engine, QWidget * parent = nullptr) explicit
Constructs a new instance.
Parameters
[in] engine The engine
parent The parent
~NotebookWidget()
NotebookWidget::~NotebookWidget ()
Destroys the object.
Member Function Documentation
close
void NotebookWidget::close () signal
Called when the user closes the notebook.
Referenced by Game::setupUi(), and setupUi().
closeActionMenu()
void NotebookWidget::closeActionMenu (bool hide = false) private
Closes the action menu.
Parameters
[in] hide Whether to hide or close
Referenced by closeCurrent().
closeCurrent()
void NotebookWidget::closeCurrent (bool hide = false) private
Closes the current widget on the stack.
Parameters
[in] hide Whether to hide or close
Referenced by displayActionMenu(), displayHistoryWidget(), displayResultsWidget(), and displaySleepWidget().
closeHistoryWidget()
void NotebookWidget::closeHistoryWidget (bool hide = false) private
Closes the history widget.
Parameters
[in] hide Whether to hide or close
Referenced by closeCurrent().
closeResultsWidget()
void NotebookWidget::closeResultsWidget (bool hide = false) private
Closes the results widget.
Parameters
[in] hide Whether to hide or close
Referenced by closeCurrent().
closeSleepWidget()
void NotebookWidget::closeSleepWidget (bool hide = false) private
Closes the sleep widget.
Parameters
[in] hide Whether to hide or close
Referenced by closeCurrent().
displayActionMenu()
void NotebookWidget::displayActionMenu (bool hide = false)
Displays the menu for selecting an action.
Parameters
[in] hide The hide
Referenced by displayPrevious(), and setupUi().
displayHistoryWidget()
void NotebookWidget::displayHistoryWidget (int day = -1, bool hide = true)
Displays the history widget for journal entries.
Parameters
[in] day The day
[in] hide The hide
Referenced by displayPrevious(), and setupUi().
displayPrevious()
void NotebookWidget::displayPrevious () private
Displays the previous widget on the stack.
Referenced by displayHistoryWidget(), displayResultsWidget(), and displaySleepWidget().
displayResultsWidget()
void NotebookWidget::displayResultsWidget (QString action, QString result, bool hide = true)
Display the results to a user.
Parameters
[in] action The action
[in] result The result
[in] hide The hide
Referenced by displayPrevious(), Game::handleActionResult(), and Game::nextDay().
displaySleepWidget()
void NotebookWidget::displaySleepWidget (bool hide = true)
Display the option for the user to sleep.
Parameters
[in] hide The hide
Referenced by displayPrevious().
explore
void NotebookWidget::explore () signal
Called when the user has opted to explore.
Referenced by displayActionMenu(), and Game::setupUi().
findFood
void NotebookWidget::findFood () signal
Called when the user has opted to find food.
Referenced by displayActionMenu(), and Game::setupUi().
findWater
void NotebookWidget::findWater () signal
Called when the user has opted to find water.
Referenced by displayActionMenu(), and Game::setupUi().
loadGraphics()
void NotebookWidget::loadGraphics () private
Loads the widget's graphics.
Referenced by NotebookWidget().
loadStylesheet()
void NotebookWidget::loadStylesheet () private
Loads a stylesheet.
Referenced by NotebookWidget().
paintEvent()
void NotebookWidget::paintEvent (QPaintEvent * event) override private
Paint event handler. See QWidget paint.
Parameters
event The event
raiseButtons()
void NotebookWidget::raiseButtons () private
Raises the buttons to be on top.
Referenced by displayActionMenu(), displayHistoryWidget(), displayResultsWidget(), and displaySleepWidget().
rest
void NotebookWidget::rest () signal
Called when the user has opted to rest.
Referenced by displayActionMenu(), and Game::setupUi().
resultAcknowledged
void NotebookWidget::resultAcknowledged () signal
Called when the user has acknowledged the result widget.
Referenced by displayResultsWidget(), and Game::setupUi().
setupUi()
void NotebookWidget::setupUi () private
Sets up the UI.
Referenced by NotebookWidget().
sleep
void NotebookWidget::sleep () signal
Called when the user has opted to sleep.
Referenced by displaySleepWidget(), and Game::setupUi().
updateDay()
void NotebookWidget::updateDay ()
Updates the day text.
Referenced by Game::updateUi().
Member Data Documentation
actionMenu
ActionMenu* NotebookWidget::actionMenu = nullptr private
Referenced by closeActionMenu(), and displayActionMenu().
background
QPixmap NotebookWidget::background private
Referenced by loadGraphics(), and paintEvent().
closeButton
SVGPushButton* NotebookWidget::closeButton private
Referenced by raiseButtons(), and setupUi().
engine
const Engine& NotebookWidget::engine private
The game engine.
Referenced by displayHistoryWidget(), setupUi(), and updateDay().
historyButton
SVGPushButton* NotebookWidget::historyButton private
Referenced by raiseButtons(), and setupUi().
historyWidget
HistoryWidget* NotebookWidget::historyWidget private
Referenced by closeHistoryWidget(), and displayHistoryWidget().
resultWidget
ResultWidget* NotebookWidget::resultWidget private
Referenced by closeResultsWidget(), and displayResultsWidget().
sleepWidget
SleepWidget* NotebookWidget::sleepWidget private
Referenced by closeSleepWidget(), and displaySleepWidget().
titleLabel
ScalableLabel* NotebookWidget::titleLabel private
Referenced by closeHistoryWidget(), displayHistoryWidget(), setupUi(), and updateDay().
widgetStack
QList<WidgetInfo> NotebookWidget::widgetStack private
Stack of widgets displayed on the notebook.
Referenced by closeCurrent(), displayActionMenu(), displayHistoryWidget(), displayPrevious(), displayResultsWidget(), and displaySleepWidget().
The documentation for this class was generated from the following files:
notebookwidget.h
notebookwidget.cpp