Survive: Animal Class Reference
Animal Class Reference
This class describes the animal instance.
#include <animal.h>
Public Member Functions
Animal (const QString &filePath)
void loadAnimalsFromJson (const QString &filePath)
const AnimalInfo & getRandomAnimal () const
const AnimalInfo & getRandomAnimalInCategory (const QString &category) const
QString getRandomAnimalCategory () const
Private Attributes
QMap< QString, QList< AnimalInfo > > animals
Detailed Description
This class describes the animal instance.
Constructor & Destructor Documentation
Animal()
Animal::Animal (const QString & filePath)
Member Function Documentation
getRandomAnimal()
const AnimalInfo & Animal::getRandomAnimal () const
Referenced by Game::exploreOption(), Engine::findFood(), and Game::findFood().
getRandomAnimalCategory()
QString Animal::getRandomAnimalCategory () const
Referenced by getRandomAnimal().
getRandomAnimalInCategory()
const AnimalInfo & Animal::getRandomAnimalInCategory (const QString & category) const
Referenced by getRandomAnimal().
loadAnimalsFromJson()
void Animal::loadAnimalsFromJson (const QString & filePath)
Referenced by Animal().
Member Data Documentation
animals
QMap<QString, QList<AnimalInfo> > Animal::animals private
Referenced by getRandomAnimalCategory(), getRandomAnimalInCategory(), and loadAnimalsFromJson().
The documentation for this class was generated from the following files:
animal.h
animal.cpp