Survive: Day Class Reference
Day Class Reference
This class describes an in-game day with climate info.
#include <day.h>
Public Member Functions
Day (const std::string &filename, const int &day=1)
Makes a new day with climate data from a JSON file.
const std::vector< ClimateData > & getMonthData (const std::string &month) const
Gets the month data.
const ClimateData & getCurrentClimateData () const
Gets the climate data for the current day.
const std::vector< ClimateData > & getMonthData (int month)
Gets the month data.
double getRandomTemperatureValue (const Temperature &temperature) const
Gets a random temperature value.
double getRandomPrecipitationValue (const Precipitation &precipitation) const
Gets a random precipitation value.
int currentDay () const
Gets the current in-game day.
int month () const
Gets the current in-game month.
QString monthId () const
Gets the current in-game month id.
void nextDay ()
Advances the day.
Static Public Member Functions
static QString monthFromInt (int month)
Convert an int value of a month to a string.
Static Public Attributes
static const std::vector< std::string > months
Private Member Functions
void loadClimateData (const std::string &filename)
Loads the climate data from a JSON.
Private Attributes
std::map< std::string, std::vector< ClimateData > > climateData
int day = 1
Detailed Description
This class describes an in-game day with climate info.
Constructor & Destructor Documentation
Day()
Day::Day (const std::string & filename, const int & day = 1)
Makes a new day with climate data from a JSON file.
See also
loadClimateData
Parameters
[in] filename The filename
Member Function Documentation
currentDay()
int Day::currentDay () const
Gets the current in-game day.
Returns
The day.
Referenced by NotebookWidget::displayHistoryWidget(), Engine::dump(), Engine::Engine(), Game::Game(), NotebookWidget::setupUi(), Engine::triggerDayEvent(), and NotebookWidget::updateDay().
getCurrentClimateData()
const ClimateData & Day::getCurrentClimateData () const
Gets the climate data for the current day.
Returns
The climate data for the current day.
Referenced by Engine::updateTemp().
getMonthData() [1/2]
const std::vector< ClimateData > & Day::getMonthData (const std::string & month) const
Gets the month data.
Parameters
[in] month The month
Returns
The month data.
Referenced by getMonthData().
getMonthData() [2/2]
const std::vector< ClimateData > & Day::getMonthData (int month)
Gets the month data.
Parameters
[in] month The month
Returns
The month data.
getRandomPrecipitationValue()
double Day::getRandomPrecipitationValue (const Precipitation & precipitation) const
Gets a random precipitation value.
Parameters
[in] precipitation The precipitation range
Returns
The random precipitation value.
getRandomTemperatureValue()
double Day::getRandomTemperatureValue (const Temperature & temperature) const
Gets a random temperature value.
Parameters
[in] temperature The temperature range
Returns
The random temperature value.
Referenced by Engine::updateTemp().
loadClimateData()
void Day::loadClimateData (const std::string & filename) private
Loads the climate data from a JSON.
Parameters
[in] filename The filename
Referenced by Day().
month()
int Day::month () const
Gets the current in-game month.
Returns
The month.
Referenced by getMonthData(), monthFromInt(), and monthId().
monthFromInt()
QString Day::monthFromInt (int month) static
Convert an int value of a month to a string.
Parameters
[in] month The month
Returns
The month id.
Referenced by monthId().
monthId()
QString Day::monthId () const
Gets the current in-game month id.
Returns
The month ID.
Referenced by getCurrentClimateData(), and Engine::triggerDayEvent().
nextDay()
void Day::nextDay ()
Advances the day.
Referenced by Engine::nextDay().
Member Data Documentation
climateData
std::map<std::string, std::vector<ClimateData> > Day::climateData private
Stores the climate data per month.
Referenced by getCurrentClimateData(), getMonthData(), and loadClimateData().
day
int Day::day = 1 private
The current day.
Referenced by currentDay(), Day(), getCurrentClimateData(), month(), and nextDay().
months
const std::vector< std::string > Day::months static
Initial value:
= {
    "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL",
    "AUG", "SEP", "OCT", "NOV", "DEC"
}
List of month IDs
Referenced by getMonthData(), and monthFromInt().
The documentation for this class was generated from the following files:
day.h
day.cpp