Survive: Plant Class Reference
Plant Class Reference
This class describe the plant instance.
#include <plant.h>
Public Member Functions
Plant (const QString &filePath)
Constructs a new instance from a JSON of plants.
void loadPlantsFromJson (const QString &filePath)
Loads the plants from a JSON.
const PlantInfo & getRandomPlant () const
Gets a random plant.
const PlantInfo & getRandomPlantInCategory (const QString &category) const
Gets a random plant in the category.
QString getRandomPlantCategory () const
Gets a random plant category.
Private Attributes
QMap< QString, QList< PlantInfo > > plants
Detailed Description
This class describe the plant instance.
Constructor & Destructor Documentation
Plant()
Plant::Plant (const QString & filePath)
Constructs a new instance from a JSON of plants.
See also
loadPlantsFromJson
Parameters
[in] filePath The file path
Member Function Documentation
getRandomPlant()
const PlantInfo & Plant::getRandomPlant () const
Gets a random plant.
Returns
The random plant.
getRandomPlantCategory()
QString Plant::getRandomPlantCategory () const
Gets a random plant category.
Returns
The random plant category.
Referenced by getRandomPlant().
getRandomPlantInCategory()
const PlantInfo & Plant::getRandomPlantInCategory (const QString & category) const
Gets a random plant in the category.
Parameters
[in] category The category
Returns
The random plant in the category.
Referenced by getRandomPlant().
loadPlantsFromJson()
void Plant::loadPlantsFromJson (const QString & filePath)
Loads the plants from a JSON.
Parameters
[in] filePath The file path
Referenced by Plant().
Member Data Documentation
plants
QMap<QString, QList<PlantInfo> > Plant::plants private
Stores the plants per category.
Referenced by getRandomPlantCategory(), and getRandomPlantInCategory().
The documentation for this class was generated from the following files:
plant.h
plant.cpp