Survive: Game Class Reference
Game Class Reference
This class describes the game instance.
#include <game.h>
Signals
void returnToMenu ()
Returns to the main menu.
Public Member Functions
Game (const QString &levelId, QWidget *parent=nullptr)
Constructs a new game instance.
~Game ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Slots
void onFindFood ()
Called on find food.
void onFindWater ()
Called on find water.
void onExplore ()
Called on explore.
void onRest ()
Called on rest.
void onResultAcknowledged ()
Called when the user has acknowledged the result.
void nextDay ()
Called when the user sleeps.
Private Member Functions
void paintEvent (QPaintEvent *event) override
Paint event handler. See QWidget paint.
void loadGraphics ()
Loads the widgets graphics.
void setupUi ()
Sets up the UI.
void updateBars ()
Update the bar elements.
void updateUi ()
Update the UI.
QString textureFile (const QString &name)
Gets a texture files path.
void handleActionResult (ActionResult result)
Handles the result of a user's action.
void endGame ()
Ends the game.
Private Attributes
Engine engine
NotebookWidget * notebookWidget
GameOver * gameOver
SVGPushButton * notebookButton
QSvgWidget * bars
QSvgWidget * healthBarFill
QSvgWidget * thirstBarFill
QSvgWidget * hungerBarFill
QSvgWidget * energyBarFill
QPixmap background
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes the game instance.
Constructor & Destructor Documentation
Game()
Game::Game (const QString & levelId, QWidget * parent = nullptr) explicit
Constructs a new game instance.
Parameters
[in] levelId The level identifier
parent The parent
~Game()
Game::~Game ()
Destroys the object.
Member Function Documentation
endGame()
void Game::endGame () private
Ends the game.
handleActionResult()
void Game::handleActionResult (ActionResult result) private
Handles the result of a user's action.
Parameters
[in] result The result
loadGraphics()
void Game::loadGraphics () private
Loads the widgets graphics.
Referenced by Game().
nextDay
void Game::nextDay () private slot
Called when the user sleeps.
Referenced by setupUi().
onExplore
void Game::onExplore () private slot
Called on explore.
Referenced by setupUi().
onFindFood
void Game::onFindFood () private slot
Called on find food.
Referenced by setupUi().
onFindWater
void Game::onFindWater () private slot
Called on find water.
Referenced by setupUi().
onRest
void Game::onRest () private slot
Called on rest.
Referenced by setupUi().
onResultAcknowledged
void Game::onResultAcknowledged () private slot
Called when the user has acknowledged the result.
Referenced by setupUi().
paintEvent()
void Game::paintEvent (QPaintEvent * event) override private
Paint event handler. See QWidget paint.
Parameters
event The event
returnToMenu
void Game::returnToMenu () signal
Returns to the main menu.
Referenced by endGame(), and SurviveGame::onNewGame().
setupUi()
void Game::setupUi () private
Sets up the UI.
Referenced by Game().
textureFile()
QString Game::textureFile (const QString & name) private
Gets a texture files path.
Parameters
[in] name The file name
Returns
The string.
Referenced by loadGraphics().
updateBars()
void Game::updateBars () private
Update the bar elements.
Referenced by updateUi().
updateUi()
void Game::updateUi () private
Update the UI.
Referenced by Game(), handleActionResult(), and nextDay().
Member Data Documentation
background
QPixmap Game::background private
Referenced by loadGraphics(), and paintEvent().
bars
QSvgWidget* Game::bars private
Referenced by setupUi().
energyBarFill
QSvgWidget* Game::energyBarFill private
Referenced by setupUi(), and updateBars().
engine
Engine Game::engine private
Game engine.
Referenced by nextDay(), setupUi(), textureFile(), and updateBars().
gameOver
GameOver* Game::gameOver private
Referenced by endGame().
healthBarFill
QSvgWidget* Game::healthBarFill private
Referenced by setupUi(), and updateBars().
hungerBarFill
QSvgWidget* Game::hungerBarFill private
Referenced by setupUi(), and updateBars().
notebookButton
SVGPushButton* Game::notebookButton private
Referenced by setupUi().
notebookWidget
NotebookWidget* Game::notebookWidget private
Referenced by handleActionResult(), nextDay(), setupUi(), and updateUi().
thirstBarFill
QSvgWidget* Game::thirstBarFill private
Referenced by setupUi(), and updateBars().
The documentation for this class was generated from the following files:
game.h
game.cpp