Survive: PauseMenu Class Reference
PauseMenu Class Reference
#include <pausemenu.h>
Public Slots
void saveSuccessful ()
Called when the save is successful.
Signals
void resume ()
Emitted when the user wants to resume.
void save ()
Emitted when the user wants to save.
void exit ()
Emitted when the user wants to exit.
Public Member Functions
PauseMenu (QWidget *parent=nullptr)
Constructs a new instance.
~PauseMenu ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Member Functions
void paintEvent (QPaintEvent *event) override
Paint event handler. See QWidget paint.
void loadGraphics ()
Loads graphics for the widget.
void setupUi ()
Sets up the UI.
Private Attributes
QSvgWidget * saveSuccessfulWidget
SVGPushButton * saveButton
SVGPushButton * exitButton
SVGPushButton * backButton
QPixmap overlay
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Constructor & Destructor Documentation
PauseMenu()
PauseMenu::PauseMenu (QWidget * parent = nullptr) explicit
Constructs a new instance.
Parameters
parent The parent
~PauseMenu()
PauseMenu::~PauseMenu ()
Destroys the object.
Member Function Documentation
exit
void PauseMenu::exit () signal
Emitted when the user wants to exit.
Referenced by Game::onPause(), and setupUi().
loadGraphics()
void PauseMenu::loadGraphics () private
Loads graphics for the widget.
Referenced by PauseMenu().
paintEvent()
void PauseMenu::paintEvent (QPaintEvent * event) override private
Paint event handler. See QWidget paint.
Parameters
event The event
resume
void PauseMenu::resume () signal
Emitted when the user wants to resume.
Referenced by Game::onPause(), and setupUi().
save
void PauseMenu::save () signal
Emitted when the user wants to save.
Referenced by Game::onPause(), and setupUi().
saveSuccessful
void PauseMenu::saveSuccessful () slot
Called when the save is successful.
Referenced by Game::onPause().
setupUi()
void PauseMenu::setupUi () private
Sets up the UI.
Referenced by PauseMenu().
Member Data Documentation
backButton
SVGPushButton* PauseMenu::backButton private
Referenced by setupUi().
exitButton
SVGPushButton* PauseMenu::exitButton private
Referenced by setupUi().
overlay
QPixmap PauseMenu::overlay private
Referenced by loadGraphics(), and paintEvent().
saveButton
SVGPushButton* PauseMenu::saveButton private
Referenced by setupUi().
saveSuccessfulWidget
QSvgWidget* PauseMenu::saveSuccessfulWidget private
Referenced by saveSuccessful(), and setupUi().
The documentation for this class was generated from the following files:
pausemenu.h
pausemenu.cpp