Survive: SleepWidget Class Reference
SleepWidget Class Reference
This class describes the notebook's sleep widget.
#include <sleepwidget.h>
Signals
void close ()
Called when the user has opted to sleep.
Public Member Functions
SleepWidget (QWidget *parent=nullptr)
Constructs a new instance.
~SleepWidget ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Member Functions
void setupUi ()
Sets up the UI.
Private Attributes
ScalableLabel * sleepLabel
SVGPushButton * sleepButton
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes the notebook's sleep widget.
Constructor & Destructor Documentation
SleepWidget()
SleepWidget::SleepWidget (QWidget * parent = nullptr) explicit
Constructs a new instance.
Parameters
parent The parent
~SleepWidget()
SleepWidget::~SleepWidget ()
Destroys the object.
Member Function Documentation
close
void SleepWidget::close () signal
Called when the user has opted to sleep.
Referenced by NotebookWidget::displaySleepWidget(), and setupUi().
setupUi()
void SleepWidget::setupUi () private
Sets up the UI.
Referenced by SleepWidget().
Member Data Documentation
sleepButton
SVGPushButton* SleepWidget::sleepButton private
Referenced by setupUi().
sleepLabel
ScalableLabel* SleepWidget::sleepLabel private
Referenced by setupUi().
The documentation for this class was generated from the following files:
sleepwidget.h
sleepwidget.cpp