Survive: ScalableWidget Class Reference
ScalableWidget Class Reference
This class describes a widget which scales it's children with the widget size.
#include <scalablewidget.h>
Classes
struct ChildInfo
Information for a child widget.
Public Member Functions
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void redraw ()
Redraw's the elements.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Private Member Functions
void setScaledGeometry (QWidget *widget)
Sets the scaled geometry. See QWidget setGeometry.
Private Attributes
QMap< QWidget *, ChildInfo > widgets
Detailed Description
This class describes a widget which scales it's children with the widget size.
Constructor & Destructor Documentation
ScalableWidget()
ScalableWidget::ScalableWidget (QWidget * parent = nullptr) explicit
Create a new scalable widget instance.
Parameters
parent The parent
~ScalableWidget()
ScalableWidget::~ScalableWidget ()
Destroys the object.
Member Function Documentation
addWidget()
void ScalableWidget::addWidget (QWidget * widget, double percentX, double percentY, double percentSizeX, double percentSizeY) protected
Adds a widget which will be scaled.
Parameters
widget The widget
[in] percentX The percent x
[in] percentY The percent y
[in] percentSizeX The percent size x
[in] percentSizeY The percent size y
Referenced by NotebookWidget::displayActionMenu(), NotebookWidget::displayHistoryWidget(), NewGameMenu::displayLevels(), MainMenu::displayLoadGameMenu(), MainMenu::displayNewGameMenu(), NotebookWidget::displayResultsWidget(), LoadGameMenu::displaySaves(), MainMenu::displaySettingsMenu(), NotebookWidget::displaySleepWidget(), Game::endGame(), MainMenu::MainMenu(), Game::setupUi(), GameOver::setupUi(), ActionMenu::setupUi(), HistoryWidget::setupUi(), NotebookWidget::setupUi(), ResultWidget::setupUi(), SleepWidget::setupUi(), LoadGameMenu::setupUi(), Menu::setupUi(), NewGameMenu::setupUi(), SettingsMenu::setupUi(), JournalDay::setupUi(), HistoryWidget::showDay(), and Game::updateBars().
redraw()
void ScalableWidget::redraw () protected
Redraw's the elements.
Referenced by DraggableWidget::mouseMoveEvent(), and resizeEvent().
removeWidget()
void ScalableWidget::removeWidget (QWidget * widget) protected
Removes a widget.
Parameters
widget The widget
Referenced by NotebookWidget::closeActionMenu(), NotebookWidget::closeHistoryWidget(), MainMenu::closeLoadGameMenu(), MainMenu::closeNewGameMenu(), NotebookWidget::closeResultsWidget(), MainMenu::closeSettingsMenu(), NotebookWidget::closeSleepWidget(), and HistoryWidget::showDay().
resizeEvent()
void ScalableWidget::resizeEvent (QResizeEvent * event) override protected
Resize event handler.
Parameters
event The event
setScaledGeometry()
void ScalableWidget::setScaledGeometry (QWidget * widget) private
Sets the scaled geometry. See QWidget setGeometry.
Parameters
widget The widget
Referenced by addWidget(), and redraw().
Member Data Documentation
widgets
QMap<QWidget*, ChildInfo> ScalableWidget::widgets private
Maps the widgets to the info.
Referenced by addWidget(), redraw(), removeWidget(), and setScaledGeometry().
The documentation for this class was generated from the following files:
scalablewidget.h
scalablewidget.cpp