Survive: Action Class Reference
Action Class Reference
#include <action.h>
Public Member Functions
Action (const QString &filePath)
void loadActionsFromJson (const QString &filePath)
const ActionInfo & getRandomAction () const
const ActionInfo & getRandomActionInCategory (const QString &category) const
QString getRandomActionCategory () const
Private Attributes
QMap< QString, QList< ActionInfo > > actions
Constructor & Destructor Documentation
Action()
Action::Action (const QString & filePath)
Member Function Documentation
getRandomAction()
const ActionInfo & Action::getRandomAction () const
Referenced by Game::relax().
getRandomActionCategory()
QString Action::getRandomActionCategory () const
Referenced by getRandomAction().
getRandomActionInCategory()
const ActionInfo & Action::getRandomActionInCategory (const QString & category) const
Referenced by getRandomAction().
loadActionsFromJson()
void Action::loadActionsFromJson (const QString & filePath)
Referenced by Action().
Member Data Documentation
actions
QMap<QString, QList<ActionInfo> > Action::actions private
Referenced by getRandomActionCategory(), getRandomActionInCategory(), and loadActionsFromJson().
The documentation for this class was generated from the following files:
action.h
action.cpp