Survive: Event Class Reference
Event Class Reference
This class contains the events.
#include <event.h>
Public Member Functions
Event (const QString &filePath)
Constructs a new instance from a JSON of events.
void loadEventsFromJson (const QString &filePath)
Loads the events from json.
QString getRandomSeason () const
Gets a random season.
const EventInfo & getRandomEvent () const
Gets a random event.
const EventInfo & getRandomEventForSeason (const QString &season) const
Gets a random event for a season.
Private Attributes
QMap< QString, QList< EventInfo > > events
Detailed Description
This class contains the events.
Constructor & Destructor Documentation
Event()
Event::Event (const QString & filePath)
Constructs a new instance from a JSON of events.
See also
loadEventsFromJson
Parameters
[in] filePath The file path
Member Function Documentation
getRandomEvent()
const EventInfo & Event::getRandomEvent () const
Gets a random event.
Returns
The random event.
Referenced by Engine::triggerDayEvent().
getRandomEventForSeason()
const EventInfo & Event::getRandomEventForSeason (const QString & season) const
Gets a random event for a season.
Parameters
[in] season The season
Returns
The random event.
Referenced by getRandomEvent(), and Engine::triggerDayEvent().
getRandomSeason()
QString Event::getRandomSeason () const
Gets a random season.
Returns
The random season.
Referenced by getRandomEvent().
loadEventsFromJson()
void Event::loadEventsFromJson (const QString & filePath)
Loads the events from json.
Parameters
[in] filePath The file path
Referenced by Event().
Member Data Documentation
events
QMap<QString, QList<EventInfo> > Event::events private
Stores the events per season.
Referenced by getRandomEventForSeason(), getRandomSeason(), and loadEventsFromJson().
The documentation for this class was generated from the following files:
event.h
event.cpp