Survive: MainMenu Class Reference
MainMenu Class Reference
This class describes the game's main menu.
#include <mainmenu.h>
Public Slots
void onNewGameButtonClicked (const QString &id)
Called when new game button clicked.
void onUiOptionChanged ()
Called when a UI option changed.
void displayNewGameMenu ()
Displays the new game menu.
void closeNewGameMenu ()
Closes the new game menu.
void displayLoadGameMenu ()
Displays the load game menu.
void closeLoadGameMenu ()
Closes the load game menu.
void displaySettingsMenu ()
Displays the settings menu.
void closeSettingsMenu ()
Closes the settings menu.
Signals
void newGameButtonClicked (const QString &id)
Emitted when a new game button is clicked.
void uiOptionChanged ()
Emitted when a UI option is changed.
Public Member Functions
MainMenu (QWidget *parent=nullptr)
Create a new main menu instance.
~MainMenu ()
Destroys the object.
Public Member Functions inherited from ScalableWidget
ScalableWidget (QWidget *parent=nullptr)
Create a new scalable widget instance.
~ScalableWidget ()
Destroys the object.
Private Attributes
NewGameMenu * newGameMenu
LoadGameMenu * loadGameMenu
SettingsMenu * settingsMenu
Menu * menu
Additional Inherited Members
Protected Member Functions inherited from ScalableWidget
void resizeEvent (QResizeEvent *event) override
Resize event handler.
void addWidget (QWidget *widget, double percentX, double percentY, double percentSizeX, double percentSizeY)
Adds a widget which will be scaled.
void removeWidget (QWidget *widget)
Removes a widget.
Detailed Description
This class describes the game's main menu.
Constructor & Destructor Documentation
MainMenu()
MainMenu::MainMenu (QWidget * parent = nullptr)
Create a new main menu instance.
Parameters
parent The parent
~MainMenu()
MainMenu::~MainMenu ()
Destroys the object.
Member Function Documentation
closeLoadGameMenu
void MainMenu::closeLoadGameMenu () slot
Closes the load game menu.
Referenced by displayLoadGameMenu().
closeNewGameMenu
void MainMenu::closeNewGameMenu () slot
Closes the new game menu.
Referenced by displayNewGameMenu(), and onNewGameButtonClicked().
closeSettingsMenu
void MainMenu::closeSettingsMenu () slot
Closes the settings menu.
Referenced by displaySettingsMenu().
displayLoadGameMenu
void MainMenu::displayLoadGameMenu () slot
Displays the load game menu.
Referenced by MainMenu().
displayNewGameMenu
void MainMenu::displayNewGameMenu () slot
Displays the new game menu.
Referenced by MainMenu().
displaySettingsMenu
void MainMenu::displaySettingsMenu () slot
Displays the settings menu.
Referenced by MainMenu().
newGameButtonClicked
void MainMenu::newGameButtonClicked (const QString & id) signal
Emitted when a new game button is clicked.
Parameters
[in] id The identifier
Referenced by onNewGameButtonClicked(), and SurviveGame::setupUi().
onNewGameButtonClicked
void MainMenu::onNewGameButtonClicked (const QString & id) slot
Called when new game button clicked.
Parameters
[in] id The identifier
Referenced by displayNewGameMenu().
onUiOptionChanged
void MainMenu::onUiOptionChanged () slot
Called when a UI option changed.
uiOptionChanged
void MainMenu::uiOptionChanged () signal
Emitted when a UI option is changed.
Referenced by displaySettingsMenu(), onUiOptionChanged(), and SurviveGame::setupUi().
Member Data Documentation
loadGameMenu
LoadGameMenu* MainMenu::loadGameMenu private
Referenced by closeLoadGameMenu(), and displayLoadGameMenu().
menu
Menu* MainMenu::menu private
Referenced by closeLoadGameMenu(), closeNewGameMenu(), closeSettingsMenu(), displayLoadGameMenu(), displayNewGameMenu(), displaySettingsMenu(), MainMenu(), and ~MainMenu().
newGameMenu
NewGameMenu* MainMenu::newGameMenu private
Referenced by closeNewGameMenu(), and displayNewGameMenu().
settingsMenu
SettingsMenu* MainMenu::settingsMenu private
Referenced by closeSettingsMenu(), and displaySettingsMenu().
The documentation for this class was generated from the following files:
mainmenu.h
mainmenu.cpp