name: "survive-build-release"

on:
    push:
        branches:
            - main
        tags:
            - v*

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
  
            - name: "Install support for Visual C++"
              uses: ilammy/msvc-dev-cmd@v1.12.1
  
            - name: "Install Qt"
              uses: jurplel/install-qt-action@v3.3.0
              with:
                    version: "6.3.2"
                    host: "windows"
                    target: "desktop"
                    arch: "win64_msvc2019_64"
                    dir: "${{ github.workspace }}/qt"

            - name: "Build Survive"
              run: |
                    mkdir build
                    cd build
                    cmake .. -A x64 -DBUILD_TESTS=OFF -DQt6_INSTALL_PREFIX="${{ github.workspace }}/qt/6.3.2/msvc2019_64"
                    cmake --build . --config Release

            - name: "Install NSIS"
              uses: repolevedavaj/install-nsis@v1.0.0
              with:
                    nsis-version: 3.09

            - name: "Create installers"
              run: |
                    cd ${{ github.workspace }}/build
                    cpack -G NSIS64 --config CPackConfig.cmake
                    cpack -G ZIP --config CPackConfig.cmake

            - name: "Configure release tag"
              if: startsWith(github.ref, 'refs/tags/v')
              run: echo "RELEASE_TAG=${{ github.ref }}" | Out-File -FilePath $env:GITHUB_ENV -Append

            - name: "Configure latest release tag"
              if: "!startsWith(github.ref, 'refs/tags/v')"
              run: echo "RELEASE_TAG=latest" | Out-File -FilePath $env:GITHUB_ENV -Append

            - name: "Publish release"
              uses: softprops/action-gh-release@v0.1.13
              with:
                token: ${{ secrets.PAT_TOKEN }}
                generate_release_notes: true
                prerelease: true
                name: "DACA: Survive - Latest"
                tag_name: ${{ env.RELEASE_TAG }}
                fail_on_unmatched_files: true
                files: |
                    "./Survive-*-*.*"

            - name: "Upload install artifact"
              uses: actions/upload-artifact@v2
              with:
                    name: "Survive"
                    path: "${{ github.workspace }}/build/Survive-*-*.zip"