name: "survive-build-release"

on:
  workflow_run:
    workflows: [survive-build-tests]
    types: [completed]
    branches: [main]

  push:
    tags: [v*, latest]


jobs:
    build-release:
        runs-on: windows-latest

        steps:
            - name: "Configure release tag"
              if: startsWith(github.ref, 'refs/tags/v')
              run: echo "RELEASE_TAG=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append

            - name: "Configure latest release tag"
              if: "!startsWith(github.ref, 'refs/tags/v')"
              run: echo "RELEASE_TAG=latest" | Out-File -FilePath $env:GITHUB_ENV -Append

            - name: "Checkout repository"
              uses: actions/checkout@v3
  
            - name: "Install support for Visual C++"
              uses: ilammy/msvc-dev-cmd@v1.12.1
  
            - name: "Install Qt"
              uses: jurplel/install-qt-action@v3.3.0
              with:
                    version: "6.3.2"
                    host: "windows"
                    target: "desktop"
                    arch: "win64_msvc2019_64"
                    dir: "${{ github.workspace }}/qt"
                    cache: true

            - name: "Build Survive"
              run: |
                    mkdir build
                    cd build
                    cmake .. -A x64 -DBUILD_TESTS=OFF -DBUILD_CLI=OFF -DBUILD_DOCUMENTATION=OFF -DQt6_INSTALL_PREFIX="${{ github.workspace }}/qt/6.3.2/msvc2019_64"
                    cmake --build . --config Release

            - name: "Install NSIS"
              uses: repolevedavaj/install-nsis@v1.0.0
              with:
                    nsis-version: 3.09

            - name: "Create installers"
              run: |
                    cd ${{ github.workspace }}/build
                    cpack -G NSIS64 --config CPackConfig.cmake
                    cpack -G ZIP --config CPackConfig.cmake

            - name: "Upload zip artifact"
              uses: actions/upload-artifact@v3
              with:
                    name: "Survive-${{ env.RELEASE_TAG }}-win64.zip"
                    path: "${{ github.workspace }}/build/Survive-*-*.zip"

            - name: "Publish release"
              uses: ncipollo/release-action@v1
              with:
                allowUpdates: true
                artifactErrorsFailBuild: true
                artifacts: "${{ github.workspace }}/build/Survive-*-*.*"
                generateReleaseNotes: true                
                name: "DACA: Survive - ${{ env.RELEASE_TAG }}"
                prerelease: true
                tag: ${{ env.RELEASE_TAG }}
                token: ${{ secrets.PAT_TOKEN }}
