name: "survive-build-tests"

on:
    [push, pull_request]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
  
            - name: "Install Qt"
              uses: jurplel/install-qt-action@v3.3.0
              with:
                    version: "6.3.2"
                    host: "linux"
                    target: "desktop"
                    arch: "gcc_64"
                    dir: "${{ github.workspace }}/qt"
                    cache: true

            - name: "Install lcov"
              run: sudo apt-get install lcov

            - name: "Build Survive with tests"
              run: |
                    mkdir build
                    cd build
                    cmake .. -DBUILD_TESTS=ON -DBUILD_DOCUMENTATION=OFF -DQt6_INSTALL_PREFIX="${{ github.workspace }}/qt/6.3.2/msvc2019_64" -DCMAKE_BUILD_TYPE=Debug
                    cmake --build . --config Debug --target Survive-Coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    fail_ci_if_error: true
                    flags: unittests
                    files: ./build/Survive-coverage.info
                    verbose: true
