name: "survive-build-tests"

on:
    [push, pull_request]

jobs:
    build-test:
        runs-on: windows-latest

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
  
            - name: "Install support for Visual C++"
              uses: ilammy/msvc-dev-cmd@v1.12.1
  
            - name: "Install Qt"
              uses: jurplel/install-qt-action@v3.3.0
              with:
                    version: "6.3.2"
                    host: "windows"
                    target: "desktop"
                    arch: "win64_msvc2019_64"
                    dir: "${{ github.workspace }}/qt"
                    cache: true

            - name: "Build Survive with tests"
              run: |
                    mkdir build
                    cd build
                    cmake .. -A x64 -DBUILD_TESTS=ON -DQt6_INSTALL_PREFIX="${{ github.workspace }}/qt/6.3.2/msvc2019_64"
                    cmake --build . --config Release --target Survive-Tests

            - name: "Run unit tests"
              shell: bash
              run: |
                    cd ${{ github.workspace }}/build
                    ./bin/Release/Survive-*-test.exe
